# Generated by Django 5.0 on 2023-12-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_descritption_review_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', upload_to='store/images'),
            preserve_default=False,
        ),
    ]
